import type { InvestorProfile } from '../types'

const now = new Date().toISOString()

/** 6 demo investors — is_demo always true (concac.txt §VI) */
export const DEMO_INVESTORS: InvestorProfile[] = [
  {
    id: 'inv-demo-preseed',
    userId: 'user-investor-demo1',
    name: 'Horizon Pre-Seed Tech',
    logoUrl: null,
    description: 'Quỹ pre-seed tập trung AI infrastructure & deeptech Đông Nam Á.',
    website: 'https://example.com/horizon-preseed',
    investorType: 'pre_seed_tech_fund',
    priorityIndustries: ['AI', 'SaaS', 'DeepTech', 'Climate'],
    preferredStages: ['idea', 'prototype', 'mvp', 'pre-seed'],
    investmentRegions: ['Vietnam', 'Southeast Asia'],
    ticketMin: 50000,
    ticketMax: 300000,
    currency: 'USD',
    investmentStyles: ['equity', 'safe'],
    riskAppetite: 'high',
    revenueRequirement: 'Pre-revenue OK',
    teamRequirement: '≥1 technical founder',
    marketRequirement: 'Clear beachhead market',
    techRequirement: 'Defensible tech or data moat',
    scalabilityRequirement: 'Path to regional scale',
    investmentThesis: 'Back technical founders building infra for the next decade of SEA digital economy.',
    exclusionCriteria: ['gambling', 'weapons', 'pure crypto trading'],
    evaluationWeights: {
      problem: 15,
      customerSegments: 10,
      uniqueValueProposition: 15,
      solution: 15,
      channels: 5,
      revenueStreams: 10,
      costStructure: 5,
      keyMetrics: 10,
      unfairAdvantage: 15,
    },
    evaluationMode: 'full',
    status: 'active',
    is_demo: true,
    createdAt: now,
  },
  {
    id: 'inv-demo-saas',
    userId: 'user-investor-demo2',
    name: 'B2B SaaS Partners',
    logoUrl: null,
    description: 'Angel syndicate focused on B2B SaaS with early MRR.',
    website: 'https://example.com/b2b-saas',
    investorType: 'saas_b2b',
    priorityIndustries: ['SaaS', 'B2B', 'FinTech', 'HRTech'],
    preferredStages: ['mvp', 'pre-seed', 'seed'],
    investmentRegions: ['Vietnam', 'Singapore'],
    ticketMin: 100000,
    ticketMax: 500000,
    currency: 'USD',
    investmentStyles: ['equity'],
    riskAppetite: 'medium',
    revenueRequirement: '≥$5k MRR preferred',
    teamRequirement: 'Sales + product duo',
    marketRequirement: 'B2B enterprise or SMB with retention',
    techRequirement: 'Product-led growth capable',
    scalabilityRequirement: 'Net revenue retention >100%',
    investmentThesis: 'Efficient SaaS with clear ICP and low CAC payback.',
    exclusionCriteria: ['consumer social', 'ad-only models'],
    evaluationWeights: {
      problem: 10,
      customerSegments: 15,
      uniqueValueProposition: 10,
      solution: 10,
      channels: 15,
      revenueStreams: 15,
      costStructure: 5,
      keyMetrics: 15,
      unfairAdvantage: 5,
    },
    evaluationMode: 'full',
    status: 'active',
    is_demo: true,
    createdAt: now,
  },
  {
    id: 'inv-demo-ecom',
    userId: 'user-investor-demo3',
    name: 'Mekong Commerce Capital',
    logoUrl: null,
    description: 'Ecommerce & marketplace specialist for Vietnam consumer brands.',
    website: 'https://example.com/mekong-commerce',
    investorType: 'ecommerce',
    priorityIndustries: ['E-commerce', 'Retail', 'Logistics', 'Consumer'],
    preferredStages: ['mvp', 'seed', 'growth'],
    investmentRegions: ['Vietnam'],
    ticketMin: 150000,
    ticketMax: 800000,
    currency: 'USD',
    investmentStyles: ['equity', 'revenue_share'],
    riskAppetite: 'medium',
    revenueRequirement: 'Traction on GMV',
    teamRequirement: 'Ops experience in retail',
    marketRequirement: 'Vietnam mass or premium niche',
    techRequirement: 'Marketplace or D2C stack',
    scalabilityRequirement: 'Unit economics path',
    investmentThesis: 'Digitize commerce rails and brands with sticky logistics.',
    exclusionCriteria: ['pure dropshipping without brand'],
    evaluationWeights: {
      problem: 10,
      customerSegments: 15,
      uniqueValueProposition: 10,
      solution: 10,
      channels: 15,
      revenueStreams: 15,
      costStructure: 10,
      keyMetrics: 10,
      unfairAdvantage: 5,
    },
    evaluationMode: 'lite',
    status: 'active',
    is_demo: true,
    createdAt: now,
  },
  {
    id: 'inv-demo-edu',
    userId: 'user-investor-demo4',
    name: 'LearnNext Ventures',
    logoUrl: null,
    description: 'Education technology and workforce upskilling investors.',
    website: 'https://example.com/learnnext',
    investorType: 'education',
    priorityIndustries: ['EdTech', 'Education', 'HRTech', 'AI'],
    preferredStages: ['prototype', 'mvp', 'pre-seed', 'seed'],
    investmentRegions: ['Vietnam', 'Southeast Asia'],
    ticketMin: 80000,
    ticketMax: 400000,
    currency: 'USD',
    investmentStyles: ['equity', 'grant_match'],
    riskAppetite: 'medium',
    revenueRequirement: 'Pilot with schools/corps OK',
    teamRequirement: 'Domain educator + tech',
    marketRequirement: 'Measurable learning outcomes',
    techRequirement: 'Content + platform',
    scalabilityRequirement: 'B2B2C or B2G path',
    investmentThesis: 'Learning products that improve employability at scale.',
    exclusionCriteria: ['predatory lending to students'],
    evaluationWeights: {
      problem: 15,
      customerSegments: 15,
      uniqueValueProposition: 15,
      solution: 10,
      channels: 10,
      revenueStreams: 10,
      costStructure: 5,
      keyMetrics: 10,
      unfairAdvantage: 10,
    },
    evaluationMode: 'full',
    status: 'active',
    is_demo: true,
    createdAt: now,
  },
  {
    id: 'inv-demo-services',
    userId: 'user-investor-demo5',
    name: 'ServiceWorks Angels',
    logoUrl: null,
    description: 'Operators investing in service marketplaces and SMB tools.',
    website: 'https://example.com/serviceworks',
    investorType: 'services',
    priorityIndustries: ['Services', 'Marketplace', 'SMB', 'PropTech'],
    preferredStages: ['mvp', 'seed'],
    investmentRegions: ['Vietnam', 'Thailand'],
    ticketMin: 100000,
    ticketMax: 350000,
    currency: 'USD',
    investmentStyles: ['equity'],
    riskAppetite: 'low',
    revenueRequirement: 'Proven transactions',
    teamRequirement: 'Ops-heavy team',
    marketRequirement: 'Local density advantage',
    techRequirement: 'Workflow automation',
    scalabilityRequirement: 'City-by-city playbook',
    investmentThesis: 'Service density + software margin in fragmented markets.',
    exclusionCriteria: ['unregulated finance'],
    evaluationWeights: {
      problem: 10,
      customerSegments: 15,
      uniqueValueProposition: 10,
      solution: 10,
      channels: 15,
      revenueStreams: 15,
      costStructure: 10,
      keyMetrics: 10,
      unfairAdvantage: 5,
    },
    evaluationMode: 'lite',
    status: 'active',
    is_demo: true,
    createdAt: now,
  },
  {
    id: 'inv-demo-impact',
    userId: 'user-investor-demo6',
    name: 'Impact Mekong Fund',
    logoUrl: null,
    description: 'Impact investor focusing climate, inclusion, and rural livelihoods.',
    website: 'https://example.com/impact-mekong',
    investorType: 'impact',
    priorityIndustries: ['Climate', 'AgriTech', 'HealthTech', 'FinInclusion'],
    preferredStages: ['mvp', 'pre-seed', 'seed', 'growth'],
    investmentRegions: ['Vietnam', 'Cambodia', 'Laos'],
    ticketMin: 75000,
    ticketMax: 600000,
    currency: 'USD',
    investmentStyles: ['equity', 'convertible', 'blended'],
    riskAppetite: 'high',
    revenueRequirement: 'Impact metrics required',
    teamRequirement: 'Mission-aligned founders',
    marketRequirement: 'Underserved communities',
    techRequirement: 'Appropriate tech for context',
    scalabilityRequirement: 'Replicable impact model',
    investmentThesis: 'Double bottom line: measurable social/climate impact + sustainable unit economics.',
    exclusionCriteria: ['fossil expansion', 'predatory microfinance'],
    evaluationWeights: {
      problem: 20,
      customerSegments: 15,
      uniqueValueProposition: 10,
      solution: 15,
      channels: 5,
      revenueStreams: 10,
      costStructure: 5,
      keyMetrics: 10,
      unfairAdvantage: 10,
    },
    evaluationMode: 'full',
    status: 'active',
    is_demo: true,
    createdAt: now,
  },
]

export const DEMO_INVESTOR_LOGINS = DEMO_INVESTORS.map((inv, i) => ({
  email: `investor.demo${i + 1}@example.com`,
  investorId: inv.id,
  // Password never stored in source — seed script uses env INVESTOR_DEMO_PASSWORD
}))
