'use client'

/**
 * Lightweight bilingual helper for the intake workspace.
 * Inline usage: tx('Tiếng Việt', 'English').
 * Dictionary usage: tx('Tiếng Việt') — falls back to VI_EN lookup so
 * module-level constants (nav labels, page titles) can stay as plain VI strings.
 */
import { useCallback, useMemo } from 'react'
import { useI18n } from '@/lib/i18n'

const VI_EN: Record<string, string> = {
  'Chương trình': 'Programs',
  'Tạo chương trình': 'New program',
  'Tổ chức': 'Organization',
  'Thư viện': 'Library',
  'Hồ sơ': 'Applications',
  'Tổng quan': 'Overview',
  'Xếp hạng': 'Ranking',
  'So sánh': 'Compare',
  'Nhật ký': 'Audit log',
  'Cài đặt': 'Settings',
  'Danh sách': 'All programs',
  'Đăng xuất': 'Sign out',
  'Đang tải…': 'Loading…',
  'Không thể tải dữ liệu': 'Could not load data',
  'Thử lại': 'Retry',
  'Công khai': 'Public',
  'Nội bộ': 'Internal',
  'Biểu mẫu nội bộ': 'Internal form',
  'Form nội bộ': 'Internal form',
  'Hoạt động': 'Activity',
  'Tạo chương trình (sự kiện)': 'Program created',
  'Tạo program': 'Program created',
  'Sửa chương trình': 'Program updated',
  'Sửa program': 'Program updated',
  'Nhận hồ sơ': 'Application received',
  'Xác nhận': 'Confirmed',
  'Quyết định': 'Decision',
  'Bắt đầu chấm': 'Screening started',
  'Xong chấm': 'Screening completed',
  'Đã nhận': 'Received',
  'Đang trích xuất': 'Extracting',
  'Cần kiểm tra': 'Needs review',
  'Sẵn sàng chấm': 'Ready to score',
  'Đã chấm': 'Scored',
  'Danh sách rút gọn': 'Shortlisted',
  'Phỏng vấn': 'Interview',
  'Được chọn': 'Accepted',
  'Không chọn': 'Rejected',
  'Lưu trữ': 'Archived',
  'Nháp': 'Draft',
  'Đang mở': 'Open',
  'Đã đóng': 'Closed',
  'Cao': 'High',
  'Trung bình': 'Medium',
  'Thấp': 'Low',
  'Làm mới': 'Refresh',
  'Tạo mới': 'Create',
  'Tìm kiếm': 'Search',
  'Lưu': 'Save',
  'Hủy': 'Cancel',
  'Mở': 'Open',
  'Chấm tất cả': 'Score all',
  'Kết quả': 'Results',
  'Điểm TB': 'Avg score',
  'Đủ điều kiện': 'Eligible',
  'chương trình': 'programs',
  'đang mở': 'open',
  'kết quả': 'results',
  'sẵn sàng chấm': 'ready to score',
  'Admin · Duyệt tài khoản': 'Admin · Account approval',
  'Chờ duyệt': 'Pending',
  'Đã duyệt': 'Active',
  'Từ chối': 'Rejected',
  'Duyệt': 'Approve',
  'So khớp': 'Matching',
  'So khớp giao thoa': 'Cross matching',
  'Báo cáo': 'Report',
  'Báo cáo nhân sự': 'Staff report',
  'Báo cáo HR': 'Staff report',
  'Báo cáo HR · Sàng lọc NIC': 'Staff report · NIC screening',
  'Nền tảng': 'Platform',
  'Chương trình hiện tại': 'Current program',
  'Không gian tiếp nhận': 'Intake workspace',
  'Tất cả chương trình': 'All programs',
  'Ghi chú': 'Notes',
  'Ghi chú nội bộ': 'Internal notes',
  'Xác nhận hồ sơ': 'Confirm profile',
  'Bật so khớp': 'Enable matching',
  'Ghi quyết định': 'Record decision',
  'Trạng thái quyết định': 'Decision status',
  'Lý do': 'Reason',
  'Thiếu dữ liệu': 'Missing data',
  'Startup nộp': 'Submitted by startup',
  'Chưa có hồ sơ trích xuất': 'No extraction profile yet',
  'Cho phép so khớp sau này': 'Allow future matching',
  'Mở trang Xếp hạng': 'Open Ranking',
  'Người chốt': 'Human final',
  'Điểm cao nhất': 'Top score',
  'Trong bộ lọc': 'Within filter',
  'Hard filter đạt': 'Hard filter pass',
  'Lượt chấm': 'Screening run',
  'Tiến độ chấm hiện tại': 'Current scoring progress',
  'chỉ tiêu': 'quota',
  'hồ sơ': 'applications',
  'Sao chép liên kết': 'Copy link',
  'Đã chép': 'Copied',
  'Liên kết nộp hồ sơ': 'Application link',
  'Mở hồ sơ': 'Open application',
  'Danh sách hồ sơ': 'Application list',
  'Chấm ngay': 'Score now',
  'Không có hồ sơ để chấm': 'No apps to score',
  'Xem danh sách hồ sơ': 'View applications',
  'Bộ lọc và chọn hồ sơ': 'Filters and selection',
  'Điểm tối thiểu': 'Min score',
  'Chỉ đủ điều kiện': 'Eligible only',
  'Đã chọn': 'Selected',
  'chờ duyệt': 'pending',
  'đã chọn': 'selected',
  'Chọn tất cả': 'Select all',
  'Duyệt đã chọn': 'Approve selected',
  'Từ chối đã chọn': 'Reject selected',
  'Không có hồ sơ chờ duyệt': 'No applications awaiting review',
  'Kiểm duyệt hồ sơ mới': 'New application moderation',
  'Phiên đăng nhập': 'Session',
  'Vai trò': 'Role',
  'Tên': 'Name',
  'Hồ sơ tổ chức': 'Organization profile',
  'Tên tổ chức': 'Organization name',
  'Mô tả': 'Description',
  'Lưu thay đổi': 'Save changes',
  'Mở trang duyệt tài khoản': 'Open account admin',
  'Hai chiều luồng giao dịch': 'Two-way deal flow',
  'Chọn định hướng chương trình': 'Pick program focus',
  'Bảng giao thoa': 'Intersection table',
  'Chỉ hồ sơ đã đồng ý so khớp': 'Opt-in only',
  'Luồng khởi nghiệp': 'Startup flow',
  'Trọng số giao thoa': 'Intersection weights',
  'Mở so khớp khởi nghiệp': 'Open startup matches',
  'Chạy lại so khớp': 'Re-run match',
  'Chạy lại': 'Re-run',
  'Chưa có giao thoa': 'No intersections yet',
  'Đang tính giao thoa…': 'Computing intersection…',
  'So khớp thất bại': 'Matching failed',
  'Ưu tiên giới thiệu': 'Prioritize introductions',
  'trong quy trình': 'in process',
  'Giai đoạn': 'Stages',
  'Thao tác': 'Actions',
  'Mở hồ sơ chi tiết': 'Open application detail',
  'Sẵn sàng so khớp': 'Matching readiness',
  'Theo chương trình': 'By program',
  'Có': 'There are',
  'hồ sơ chờ duyệt': 'applications pending review',
  'mở kiểm duyệt': 'open moderation',
  'Trong không gian làm việc': 'In this workspace',
  'Chưa công khai': 'Not public yet',
  'Tổng chỉ tiêu chọn': 'Total selection quota',
  'Phân bố trạng thái chương trình': 'Program status distribution',
  'Sẵn sàng luồng giao dịch': 'Deal-flow readiness',
  'Quy trình tiếp nhận': 'Intake process',
  'Bấm để mở tổng quan': 'Click to open overview',
  'Tạo chương trình đầu tiên để nhận hồ sơ và chạy chấm điểm.':
    'Create your first program to receive applications and run scoring.',
  'Tổng chương trình': 'Total programs',
  'Bản nháp': 'Drafts',
  'Chỉ tiêu chọn': 'Selection quota',
  'Đóng': 'Closed',
  'Luồng giao dịch NIC': 'NIC deal flow',
  'Đã đồng ý so khớp': 'Matching opt-in',
  'Độ khớp từ 80': 'Fit 80+',
  'Độ khớp 60 đến 79': 'Fit 60 to 79',
}

export function useTx() {
  const { lang, toggleLang } = useI18n()
  // Stable identity — prevents useCallback([tx]) + useEffect(load) infinite refetch loops
  const tx = useCallback(
    (vi: string, en?: string) => (lang === 'vi' ? vi : (en ?? VI_EN[vi] ?? vi)),
    [lang],
  )
  return useMemo(() => ({ tx, lang, toggleLang }), [tx, lang, toggleLang])
}
